#!/bin/sh
# Need to perform product enablement 

id="5737-I22"
enablementText="PRODUCT OWNER('IBM CORP')               
        NAME('IBM Z OPEN DEV')              
        ID(${id})                    
        VERSION(*) RELEASE(*) MOD(*)    
        FEATURENAME('Dependency-Based-Build')
        STATE(ENABLED)"

out=$(whence zbrewinternalfuncs >/dev/null)
if [ $? -eq 0 ]; then
	. zbrewinternalfuncs
else    	
	echo "zbrew tools need to be in your PATH" >&2
	exit 4
fi
out=$(whence zbrewexternalfuncs >/dev/null)
if [ $? -eq 0 ]; then
	. zbrewexternalfuncs
else    	
	echo "zbrew tools need to be in your PATH" >&2
	exit 4
fi

swregistrar "bgz106" "enable" "${id}" "${enablementText}"
rc=$?
exit $rc
