#!/bin/sh
# Need to perform product disablement 

id="5737-I22"

out=$(whence zbrewexternalfuncs >/dev/null)
if [ $? -eq 0 ]; then
	. zbrewexternalfuncs
else    	
	echo "zbrew tools need to be in your PATH" >&2
	exit 4
fi

swregistrar "bgz106" "disable" "${id}"
rc=$?
exit $rc
