#!/bin/sh
# Need to perform product enablement 

id="5737-I22"
enablementText="
PRODUCT OWNER('IBM CORP')               
        NAME('IBM Z OPEN DEV')              
        ID(${id})                    
        VERSION(*) RELEASE(*) MOD(*)    
        FEATURENAME(*)
        STATE(ENABLED)"

out=$(whence zbrewfuncs >/dev/null)
if [ $? -eq 0 ]; then
	. zbrewfuncs
else
    	echo "zbrew tools need to be in your PATH"
	exit 4
fi

swregistrar "enable" "${id}" "${enablementText}"
rc=$?
exit $rc
mydir=$(callerdir ${0})
props="${mydir}/../../zbrew/properties/globalprops.json"
zbrewpropse zbrew global "${props}"

props="${mydir}/../../zbrew/properties/zbrewprops.json"
zbrewpropse zbrew config "${props}"



exit 0
